[clovers]
plugins = ["clovers_setu_collection"]
# plugin_dirs = [ "./src/clovers/plugins"]

[clovers_setu_collection]
# 是否保存从api获取的图片
save_image = false
# 主路径
path = "data/setu_collection"
# 私聊图片限制
private_setu_limit = true
# 私聊使用的图片api
private_setu_api  = "Lolicon API"
# 群聊图片限制（别关）
public_setu_limit = true
# 群聊使用的图片api
public_setu_api = "Lolicon API"

# LoliconAPI  httpx 配置
[clovers_setu_collection.httpx_config.LoliconAPI]
proxy = "http://172.16.20.203:20172"

# MirlKoiAPI httpx 配置
[clovers_setu_collection.httpx_config.MirlKoiAPI]
proxy = "http://172.16.20.203:20172"

# AnosuAPI httpx 配置
[clovers_setu_collection.httpx_config.AnosuAPI]
proxy = "http://172.16.20.203:20172"
