name: ci

on:
  push:
    tags:
      - 'v*'
      - 'V*'

jobs:
  docker:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: trytodupe/ttd-bot:${{ github.ref_name }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Add host key
        run: |
          ssh-keyscan ${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          tailscale ssh github@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }}
                    "${{ secrets.DEPLOY_SCRIPT }} ${{ github.ref_name }}"
